flags: {}
packages:
- '.'
extra-deps: 
# - inline-c-0.5.5.3

# resolver: lts-1.0            # ghc-7.8.4
# resolver: lts-5.15           # ghc-7.10.3
resolver: lts-21.25 # ghc-9.4.8

ghc-options:
  "*": -fno-warn-missing-signatures -fno-warn-unused-do-bind -fno-warn-unused-imports